### ISSUE TITLE
marisa 以外のなにかをつかうように変更する。

### ISSUE THREAD

**Issue by tokuhirom** [akaza-im/akaza#125]
現在、モデルファイルを marisa で作成しているが、もはや別に TRIE ではなく KVS としてつかっているので他のなにかにしたい。

要件: 

- pure rust
  - C/C++ ライブラリへの依存がない
- エンディアンに依存しない

https://github.com/estebank/galvanize cdbのファイルとかもあるので、こういうの使うんでもいいかも。
CDBは32bit little endian 固定なので。

_Originally posted by @tokuhirom in https://github.com/tokuhirom/akaza/issues/70#issuecomment-1383044757_

**Comment by tokuhirom** [comment]
oh

**Comment by tokuhirom** [comment]
CDB だからエンディアン非依存やろ、と思ってましたがまさかの。。ｗ

**Comment by omasanori** [comment]
> ところでgalvanizeのシリアライズ/デシリアライズはエンディアン非依存になってないかも？

いや、私の勘違いでした。すみません。このコードはリトルエンディアンとビッグエンディアンの両方でリトルエンディアンのバイト列とネイティブの`u32`の間の変換を行います。

（Rust 1.32から`to_le_bytes`や`from_le_bytes`といった関数が使えるので自分で実装する必要も特にないのですが、支障はないです。）

**Comment by tokuhirom** [comment]
とはいえビッグエンディアンのCPU使うケースもあんまないのと、MARISAほど圧縮きいて丁度いいライブラリもないのかもしれない。。

**Comment by tokuhirom** [comment]
一旦検討終わり。
