### ISSUE TITLE
ライセンス

### ISSUE THREAD

**Issue by Misaka13514** [akaza-im/akaza#212]
このリポジトリのライセンスは MIT のようですが、`LICENSE` ファイルは 853cb492ab98602b6436b59feef0e5f3c83f74f4 で削除されました。
[ライセンスが表記](https://docs.github.com/ja/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)されていれば、他の開発者が理解しやすくなり、ソフトウェアの配布も容易になりますので、是非ご検討ください。

**Comment by Misaka13514** [comment]
ありがとうございます。

**Comment by tokuhirom** [comment]
おっと。そのファイルはモデルデータの配布用の LICENSE ファイルなので、モデルデータを分離する経緯があって消したというやつでした。
README に LICENSE については記述されていたものの、ご指摘のとおり LICENSE ファイルがあったほうがわかりやすいと思いますので、追加しました〜
