### ISSUE TITLE
キーレイアウトを設定できるようにする

### ISSUE THREAD

**Issue by tokuhirom** [akaza-im/akaza#244]
今は us 固定。

**Comment by tokuhirom** [comment]
```
km = ibus_keymap_get("us");
ibus_lookup_keysym(km, keycode, state)
```

というふうに、毎回キーマップからキーシンボルを得るようにすればいいっぽい?

**Comment by tkng** [comment]
ibusには詳しくないので、なぜレイアウトの設定をしないといけないのかよくわからないのですが、現状、ibus-akazaを有効にすると、キーボードレイアウトが強制的にusに変更されます。

https://github.com/akaza-im/akaza/blob/d4697b3361ae5aa596bb1e54eb8767848237deb8/ibus-akaza/wrapper.c#L139 の"us" を"default"に変更すると、上記の問題は解消されます。

ibusのドキュメントを確認してみたところ、

https://github.com/ibus/ibus/blob/2a235c8c33f1de56df4873fe3662d5beb1355715/src/ibusenginedesc.h#L111 には

> If layout is "default", the engine inherits the current layout and does not change the layout. The layouts "default" and "" are same.

とあるので、とりあえず、"default"か""にしておくのが無難そうに思います。

**Comment by tokuhirom** [comment]
おぉ。なるほど。。
なんだか ibus-anthy にせよなんにせよ、設定でキーレイアウトを変えられるようになっていたので、変えるのが大前提何だと思っていたのですが、default で設定できるならそれで良さそうですね
