### ISSUE TITLE
config.ymlがない

### ISSUE THREAD

**Issue by tkng** [akaza-im/akaza#245]
config.ymlがrepository上にないので、現状では、動作させるために、自分でそれっぽいconfig.ymlを書く必要があります。

**Comment by tokuhirom** [comment]
Oops... 設定ファイルがなくても起動するように設定していたつもりだったのですが、Modelファイルのパス指定が /unigram.model を見てしまってますね。

**Comment by tokuhirom** [comment]
`Config::default()` だと serde の ` #[serde(default = "default_model")]` が読まれないので、config.yml がない場合は serde 経由でオブジェクトを読むようにしました。これで config.yml がなくても起動するようになったはずです。 #251
