### ISSUE TITLE
SKK-JISYO.Lのパスを指定しなくても自動的に読み込んでほしい

### ISSUE THREAD

**Issue by tkng** [akaza-im/akaza#258]
SKK-JISYO.akazaにはSKK-JISYO.Lに入っている語彙は含まれていないので、akazaの動作には、事実上、SKK-JISYO.Lが必須です。しかし、現状、SKK-JISYO.Lを読み込むには、config.ymlに明示するしか手がありません。

`/usr/share/skk/` あたりから自動で読み込んでほしいなという気持ちがあります。

**Comment by tokuhirom** [comment]
たしかに、config.yml に辞書の設定がなければ /usr/share/skk/SKK-JISYO.L を読むようにしてしまうのがよさそうです。

(akaza-conf の設定ツールから設定すれば一応読めるのですが、起動時の状態だとだいぶ語彙が少なくて使いにくい状態になっています。
開発初期には SKK-JISYO.L を SKK-JISYO.akaza に混ぜ込んでいたのでこういった問題は起きていなかったのですが、ライセンス関連を分かりやすくするために分離したという経緯があります。)
